# Generated by Django 5.1 on 2024-09-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_normalized", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("film_number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_normalized", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("rating", models.IntegerField()),
                (
                    "actors",
                    models.ManyToManyField(related_name="films", to="app.actor"),
                ),
            ],
        ),
    ]
